---
- name: First setup
  hosts: local
  become: true

  tasks:
    - name: Install common package
      ansible.builtin.package:
        name:
          - zsh
          - wget
          - curl
          - git
          - make
          - gcc
        state: present

    - name: Change a shell to zsh
      ansible.builtin.blockinfile:
        destfile: /etc/shells
        block: /usr/bin/zsh

- name: Install Neovim
  tasks:
  - name: Check inside container
    ansible.builtin.command: "grep -qi 'docker' /proc/1/cgroup"
    register: container_detect
    changed_when: false
    failed_when: false

  - name: Set env type
    ansible.builtin.set_fact:
      env_type: >-
        {% if container_detect.rc == 0 %}
          container
        {% else %}
          baremetal
        {% endif %}

  - name: Disply env type
    ansible.builtin.debug:
      msg: "Environment is {{ env_type }}"

  - name: Install package if on baremetal env
    when: env_type == "baremetal"
    ansible.builtin.package:
      name:
        - neovim
        - ripgrep
        - unzip
        - xclip
      state: present

